# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
import pytest
from selenium.common import NoSuchElementException, ElementNotInteractableException, InvalidElementStateException, \
    ElementNotVisibleException, StaleElementReferenceException, TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome import webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_alii(self):
    self.driver.get("https://login.aliexpress.com/")
    self.driver.set_window_size(656, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".comet-tabs-nav-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comet-input-focused").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comet-input-focused").send_keys("tamerassi11@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".comet-input-focused").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comet-input-focused").send_keys("asd123+!")
    self.driver.find_element(By.ID, "root").click()
    self.driver.find_element(By.CSS_SELECTOR, ".create-submit").click()
  
